ARCEE_MODELS = {
    "trinity-large-thinking": {
        "id": "trinity-large-thinking",
        "name": "trinity-large-thinking",
        "api_base": "https://api.arcee.ai/api/v1",
        "api_key_env_var": "ARCEE_API_KEY",
        "supports_json": True,
        "supports_logprobs": False,
        "supports_responses": False,
        "api_spec": "openai",
        "input_cost": 0.25,
        "cached_input_cost": 0.25,
        "output_cost": 0.90,
        "reasoning_model": True,
    },
    "trinity-large-preview": {
        "id": "trinity-mini",
        "name": "trinity-mini",
        "api_base": "https://api.arcee.ai/api/v1",
        "api_key_env_var": "ARCEE_API_KEY",
        "supports_json": True,
        "supports_logprobs": False,
        "supports_responses": False,
        "api_spec": "openai",
        "input_cost": 0.25,
        "cached_input_cost": 0.25,
        "output_cost": 1.00,
        "reasoning_model": True,
    },
    "trinity-mini": {
        "id": "trinity-mini",
        "name": "trinity-mini",
        "api_base": "https://api.arcee.ai/api/v1",
        "api_key_env_var": "ARCEE_API_KEY",
        "supports_json": True,
        "supports_logprobs": False,
        "supports_responses": False,
        "api_spec": "openai",
        "input_cost": 0.045,
        "cached_input_cost": 0.045,
        "output_cost": 0.15,
        "reasoning_model": True,
    },
}
