NVIDIA_MODELS = {
    "gpt-oss-20b-nvidia": {
        "id": "gpt-oss-20b-nvidia",
        "name": "openai/gpt-oss-20b",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "supports_json": True,
        "reasoning_model": True,
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "gpt-oss-120b-nvidia": {
        "id": "gpt-oss-120b-nvidia",
        "name": "openai/gpt-oss-120b",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "supports_json": True,
        "reasoning_model": True,
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "minimax-m2.7-nvidia": {
        "id": "minimax-m2.7-nvidia",
        "name": "minimaxai/minimax-m2.7",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "deepseek-3.2-nvidia": {
        "id": "deepseek-3.2-nvidia",
        "name": "deepseek-ai/deepseek-v3.2",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "supports_json": True,
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "kimi-k2.5-nvidia": {
        "id": "kimi-k2.5-nvidia",
        "name": "moonshotai/kimi-k2.5",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "supports_images": True,
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "sarvam-m-nvidia": {
        "id": "sarvam-m-nvidia",
        "name": "sarvamai/sarvam-m",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "glm-4.7-nvidia": {
        "id": "glm-4.7-nvidia",
        "name": "z-ai/glm4.7",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "supports_json": True,
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "glm-5.1-nvidia": {
        "id": "glm-5.1-nvidia",
        "name": "z-ai/glm-5.1",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
    "nemotron-3-super-120b-a12b-nvidia": {
        "id": "nemotron-3-super-120b-a12b-nvidia",
        "name": "nvidia/nemotron-3-super-120b-a12b",
        "api_base": "https://integrate.api.nvidia.com/v1",
        "api_key_env_var": "NVIDIA_API_KEY",
        "api_spec": "nvidia",
        "input_cost": 0.0,
        "cached_input_cost": 0.0,
        "cache_write_cost": 0.0,
        "output_cost": 0.0,
    },
}
