OPENROUTER_MODELS = {
    "glm-4.6-openrouter": {
        "id": "glm-4.6-openrouter",
        "name": "z-ai/glm-4.6",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key_env_var": "OPENROUTER_API_KEY",
        "supports_json": True,
        "api_spec": "openai",
        "input_cost": 0.6,
        "cached_input_cost": 0.11,
        "cache_write_cost": 0.6,
        "output_cost": 2.20,
    },
    "deepseek-r1-openrouter": {
        "id": "deepseek-r1-openrouter",
        "name": "deepseek/deepseek-r1-0528",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key_env_var": "OPENROUTER_API_KEY",
        "supports_json": True,
        "api_spec": "openai",
        "input_cost": 0.40,
        "cached_input_cost": 0.40,
        "cache_write_cost": 0.40,
        "output_cost": 1.75,
    },
    "deepseek-3.1-openrouter": {
        "id": "deepseek-3.1-openrouter",
        "name": "deepseek/deepseek-v3.1-terminus",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key_env_var": "OPENROUTER_API_KEY",
        "supports_json": True,
        "api_spec": "openai",
        "input_cost": 0.23,
        "cached_input_cost": 0.23,
        "cache_write_cost": 0.23,
        "output_cost": 0.9,
    },
    "deepseek-3.2-openrouter": {
        "id": "deepseek-3.2-openrouter",
        "name": "deepseek/deepseek-v3.2-exp",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key_env_var": "OPENROUTER_API_KEY",
        "supports_json": True,
        "api_spec": "openai",
        "input_cost": 0.27,
        "cached_input_cost": 0.27,
        "cache_write_cost": 0.27,
        "output_cost": 0.4,
    },
    # "gpt-oss-20b-openrouter": {},
    # "gpt-oss-120b-openrouter": {},
    "kimi-k2-openrouter": {
        "id": "kimi-k2-openrouter",
        "name": "z-ai/glm-4.6",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key_env_var": "OPENROUTER_API_KEY",
        "supports_json": True,
        "api_spec": "openai",
        "input_cost": 0.6,
        "cached_input_cost": 0.11,
        "cache_write_cost": 0.6,
        "output_cost": 2.20,
    },
}
