PERCEPTRON_MODELS = {
    "perceptron-mk1": {
        "id": "perceptron-mk1",
        "name": "perceptron-mk1",
        "api_base": "https://api.perceptron.inc/v1",
        "api_key_env_var": "PERCEPTRON_API_KEY",
        "api_spec": "openai",
        "supports_json": True,
        "supports_images": True,
        "input_cost": 0.15,
        "output_cost": 1.50,
        "omit_default_sampling_params": True,
    },
    "isaac-0.2-2b-preview": {
        "id": "isaac-0.2-2b-preview",
        "name": "isaac-0.2-2b-preview",
        "api_base": "https://api.perceptron.inc/v1",
        "api_key_env_var": "PERCEPTRON_API_KEY",
        "api_spec": "openai",
        "supports_json": True,
        "supports_images": True,
        "input_cost": 0.15,
        "output_cost": 1.25,
        "omit_default_sampling_params": True,
    },
    "isaac-0.2-1b": {
        "id": "isaac-0.2-1b",
        "name": "isaac-0.2-1b",
        "api_base": "https://api.perceptron.inc/v1",
        "api_key_env_var": "PERCEPTRON_API_KEY",
        "api_spec": "openai",
        "supports_json": True,
        "supports_images": True,
        "input_cost": 0.15,
        "output_cost": 1.25,
        "omit_default_sampling_params": True,
    },
    "isaac-0.1": {
        "id": "isaac-0.1",
        "name": "isaac-0.1",
        "api_base": "https://api.perceptron.inc/v1",
        "api_key_env_var": "PERCEPTRON_API_KEY",
        "api_spec": "openai",
        "supports_json": True,
        "supports_images": True,
        "input_cost": 0.15,
        "output_cost": 1.25,
        "omit_default_sampling_params": True,
    },
}
